tcserver:
  version: 2.8.+
  repository_root: "http://192.168.62.1:8080/app/repo/tcserver"
lifecycle_support:
  version: 2.+
  repository_root: "{default.repository.root}/tomcat-lifecycle-support"
logging_support:
  version: 2.+
  repository_root: "{default.repository.root}/tomcat-logging-support"